"""Updated user and category model

Revision ID: 3bda40537480
Revises: bf45a15da217
Create Date: 2026-08-19 14:56:21.069303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bda40537480'
down_revision: Union[str, Sequence[str], None] = 'bf45a15da217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at::timestamp with time zone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False,
               postgresql_using="created_at::varchar")
    # ### end Alembic commands ###
