name: Deploy Bookbudi API

on:
  push:
    branches:
      - dev
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

  GAR_REPOSITORY: bookbudi-repo
  IMAGE_NAME: fastapi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # --------------------------------
      # Checkout
      # --------------------------------
      - name: Checkout code
        uses: actions/checkout@v4


      # --------------------------------
      # Set environment based on branch
      # --------------------------------
      - name: Set deployment environment
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "NAMESPACE=dev" >> $GITHUB_ENV
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "NAMESPACE=prd" >> $GITHUB_ENV
            echo "ENVIRONMENT=prd" >> $GITHUB_ENV
          else
            echo "Unsupported branch"
            exit 1
          fi

      # --------------------------------
      # Show environment
      # --------------------------------
      - name: Show deployment information
        run: |
          echo "Branch: $GITHUB_REF_NAME"
          echo "Environment: $ENVIRONMENT"
          echo "Namespace: $NAMESPACE"


      # --------------------------------
      # Authenticate with GCP
      # --------------------------------
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'


      # --------------------------------
      # Setup gcloud
      # --------------------------------
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2


      # --------------------------------
      # Configure Docker
      # --------------------------------
      - name: Configure Docker
        run: |
          gcloud auth configure-docker \
            ${{ env.REGION }}-docker.pkg.dev


      # --------------------------------
      # Build Docker image
      # --------------------------------
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            .


      # --------------------------------
      # Push Docker image
      # --------------------------------
      - name: Push Docker image
        run: |
          docker push \
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}


      # --------------------------------
      # Get GKE credentials
      # --------------------------------
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.REGION }}


      # --------------------------------
      # Create namespace
      # --------------------------------
      - name: Create namespace
        run: |
          kubectl create namespace $NAMESPACE \
            --dry-run=client \
            -o yaml | kubectl apply -f -

      # --------------------------------
      # Create / Update Kubernetes Secrets
      # --------------------------------
      - name: Create Kubernetes Secret
        env:
          DB_URL: ${{ github.ref_name == 'main' && secrets.PRD_DB_URL || secrets.DEV_DB_URL }}
          FIREBASE_SA: ${{ github.ref_name == 'main' && secrets.PRD_SERVICE_ACCOUNT || secrets.DEV_SERVICE_ACCOUNT }}

        run: |
          kubectl create secret generic bookbudi-secrets \
            --namespace $NAMESPACE \
            --from-literal=DB_URL="$DB_URL" \
            --from-literal=FIREBASE_SERVICE_ACCOUNT_JSON="$FIREBASE_SA" \
            --dry-run=client \
            -o yaml | kubectl apply -f -


      # --------------------------------
      # Deploy Kubernetes resources
      # --------------------------------
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply \
            -n $NAMESPACE \
            -f k8s/deployment.yaml

          kubectl apply \
            -n $NAMESPACE \
            -f k8s/service.yaml

      # Set APP_ENV
      - name: Set application environment
        run: |
          kubectl -n $NAMESPACE set env deployment/bookbudi-api \
            APP_ENV=$ENVIRONMENT


      # --------------------------------
      # Update Docker image
      # --------------------------------
      - name: Update deployment image
        run: |
          kubectl -n $NAMESPACE set image deployment/bookbudi-api \
            bookbudi-api=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}


      # --------------------------------
      # Wait for deployment
      # --------------------------------
      - name: Wait for deployment
        run: |
          kubectl -n $NAMESPACE rollout status deployment/bookbudi-api